# Generated by Django 3.1.4 on 2020-12-05 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ogzn', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feedback_email',
            field=models.EmailField(blank=True, max_length=30, verbose_name='E-mail'),
        ),
    ]
